config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :session, only: [:show]
  resources :categories
  resources :articles
  resources :letter, only: [:index] do
    collection do
      get :render_letter
      post :render_letter
    end
  end
  resources :sign_images, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category

  validates :title, :content, :category_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/sign_image.rb
class SignImage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper
  include ApplicationHelper
  include Pagy::Backend
  helper_method :categories
  add_flash_types :info, :error, :warning

  before_action :turbo_frame_request_variant, :apply_cookie_key!

  def categories
    @categories ||= Category.all
  end

  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/articles_controller.rb
require 'redcarpet/compat'

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]

  def index
    @articles = Article.all.includes(:category).order(created_at: :desc)
    @articles = @articles.where(category_id: params[:category_id]) if params[:category_id].present?
    @pagy, @articles = pagy(@articles, items: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:blue] = 'Article was successfully created.'
      redirect_to @article
    else
      flash[:red] = 'Article was not created.'
      render 'new'
    end
  end

  def destroy
    if @article.present? && @article.destroy
      flash[:blue] = 'Article successfully deleted'
    else
      flash[:red] = @article&.errors&.full_messages
    end
    redirect_to root_path
  end

  def show; end

  def update
    flash[:blue] = 'Article was sucessfully updated' if @article.update(article_params)

    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index; end

  def show
    @category = Category.find_by(id: params[:id])
    @pagy, @articles = pagy(@category.articles.includes(:category).order(created_at: :desc), items: 5)

    render 'home/index'
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:blue] = 'Category was successfully created.'
      redirect_to root_path
    else
      flash.now[:red] = 'Category was not created.'
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pagy, @articles = pagy(Article.all.includes(:category).order(created_at: :desc), items: 5)
  end
end

app/controllers/letter_controller.rb
class LetterController < ApplicationController 
  def index
    render layout: false
  end

  def render_letter
    render '_letter', layout: false, status: :ok
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # bro, check here, this is how I login, understand now?
  def show
    raise ActionController::RoutingError, 'Session not found' unless verify!(params[:id])

    redirect_to root_path, allow_other_host: true
  end
end

app/controllers/sign_images_controller.rb
class SignImagesController < ApplicationController
  skip_before_action :verify_authenticity_token  

  def create
    sign_image_params = params[:sign_image].permit(:src)
    @sign_image = SignImage.new(sign_image_params)

    @sign_image.save!

    respond_to do |format|
      format.json { render json: @sign_image, status: :created }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  class HTMLWithPants < Redcarpet::Render::HTML
    include Redcarpet::Render::SmartyPants
  end

  def markdown
    @markdown ||= Redcarpet::Markdown.new(HTMLWithPants.new(hard_wrap: true, prettify: true), fenced_code_blocks: true)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  MEETING_DAY = [2022, 02, 07]

  def days_distances
    meeting_day = Date.new(*MEETING_DAY)

    Date.today.mjd - meeting_day.mjd
  end
end

app/helpers/letter_helper.rb
module LetterHelper
end

app/helpers/session_helper.rb
module SessionHelper
  # Read key from cookies
  def apply_cookie_key!
    session[:door_key] = cookies[:door_key] if cookies[:door_key]
  end

  # Verify if the provided door_key is valid, and set to cookie
  def verify!(door_key)
    return false unless door_key == Rails.configuration.door_key

    session[:door_key] = door_key
    cookies[:door_key] = {
      value: door_key,
      expires: 30.days.from_now,
      secure: false,
      httponly: false
    }
  end

  # check if the session[:door_key] is set
  def verified?
    session[:door_key].present? && session[:door_key] == cookies[:door_key]
  end
end

app/helpers/sign_images_helper.rb
module SignImagesHelper
end

app/views/articles/_article.html.erb
<div class="mb-6">
  <div id="<%= dom_id article %>" class="max-w-4xl ">
      <div class="mb-2 py-6 px-10 shadow-md post-card rounded-lg">
        <a href="/articles/<%= article.id %>">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= article.title %></h5>
            <div class="flex justify-between items-center">
              <span class="font-light text-gray-600"><%= article.updated_at.strftime('%Y-%m-%d') %></span>
              <%= link_to article.category.name, article.category, class: 'px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500' %>
            </div>
            <div class="mt-2 max-h-40 overflow-hidden">
              <div class="mt-2 text-gray-600"><%= raw markdown.render article.content %>...</div>
            </div>
            <% if verified? %>
              <div class="flex justify-between items-center mt-4">
                <%= link_to t('delete'), article, class: 'text-blue-500 hover:underline', data: { "turbo-method": :delete }  %>
              </div>
            <% end %>
        </a>
      </div>
  </div>
</div>

app/views/articles/_pager.html.erb
<div id="pager" class="min-w-full my-8 flex justify-center">
  <div>
    <% if pagy.next %>
      <%= link_to(
        "Load more articles",
        root_path(page: pagy.next),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_frame: "page_handler",
          controller: "autoclick"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/articles/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
    "append",
    target: "articles",
    template: %(#{render @articles}) 
  ) %>
  <%= turbo_stream_action_tag(
    "replace",
    target: "pager",
    template: %(#{render "pager", pagy: @pagy})
    ) %>
<% end %>

app/views/articles/index.html.erb
<div class="flex items-center justify-between">
  <h1 class="text-xl font-bold text-gray-700 md:text-2xl"><%= t("post") %></h1>
</div>

<div class="mt-6">
  <%= turbo_frame_tag "page_handler" %>
  <div id="articles">
    <%= render @articles %>
  </div>
  <%= render "home/pager", pagy: @pagy %>
</div>

app/views/articles/new.html.erb
<%= form_with model: @article, class:  "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", data: { turbo: false } do |f| %>
  <div class="mb-4">
    <%= f.label :title, 'Title', class: 'block text-gray-700 text-sm font-bold mb-2' %>
    <%= f.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
  </div>

  <div class="mb-4">
    <%= f.label :title, 'Category', class: 'block text-gray-700 text-sm font-bold mb-2' %>
    <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]}, {} ,class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= f.label :content, 'Body', class: 'block text-gray-700 text-sm font-bold mb-2' %>
    <%= f.text_area :content, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', rows: '30' %>
  </div>
  
  <div class="flex items-center justify-between">
    <%= f.submit 'Submit', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<!--Container-->
<div class="container w-full md:max-w-3xl mx-auto pt-5">

  <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family:Georgia,serif;">
    <!--Title-->
    <div class="font-sans">
      <div id="show-block">
        <p class="text-base md:text-sm text-blue-500 font-bold">&lt; <a href="/articles" class="text-base md:text-sm text-blue-500 font-bold no-underline hover:underline"><%= t('back_to_blog') %></a></p>
        <h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl"><%= @article.title %></h1>
        <br>
        <p class="inline  text-sm md:text-base font-normal text-gray-600">Published <%= @article.created_at.strftime('%Y-%m-%d') %></p>
        <% if verified? %>
          <span class="inline text-sm md:text-base font-normal text-blue-600 cursor-pointer edit-article" id="edit">edit</span>
        <% end %>
        <br>
        <!--Post Content-->
        <div class="post-content prose" id="article-content">
          <%= raw markdown.render @article.content %>
        </div>
      </div>
      <div style="display:none" id="edit-block">
        <%= form_with model: @article, method: 'put', class:  "", data: { turbo: false } do |f| %>
          <div class="mb-4">
            <%= f.label :title, 'Title', class: 'block text-gray-700 text-sm font-bold mb-2' %>
            <%= f.text_field :title, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
          </div>

          <div class="mb-4">
            <%= f.label :title, 'Category', class: 'block text-gray-700 text-sm font-bold mb-2' %>
            <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]}, {} ,class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
          </div>

          <div class="mb-4">
            <%= f.label :content, 'Body', class: 'block text-gray-700 text-sm font-bold mb-2' %>
            <%= f.text_area :content, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', rows: '30' %>
          </div>
          
          <div class="flex items-center justify-between">
            <%= f.submit 'Submit', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
editBtn = document.querySelector('.edit-article');

if (editBtn) {
  editBtn.addEventListener('click', () => {
    document.querySelector('#edit-block').style.display = 'block'
    document.querySelector('#show-block').style.display = 'none'
  })
}
</script>

app/views/categories/new.html.erb
<%= form_with model: @category, class:  "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |f| %>
  <div class="mb-4">
    <%= f.label :name, 'Category name', class: 'block text-gray-700 text-sm font-bold mb-2' %>
    <%= f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
  </div>
  
  <div class="flex items-center justify-between">
    <%= f.submit 'Submit', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="logo-container">
  <div class="">
    <%= image_tag 'coffee.png', class: 'big-logo heart', id: 'pixel_heart' %>
  </div>
</div>
<div class="post-card text-center hello-card rounded-lg">
  <div class="mr-3">
    ✨ Hello, I'm Barry Huang. I graduated from the Royal Melbourne Institute of Technology in Information Technology.
    I'm currently located in Guangzhou, China, working as a ruby developer.
    I have a passion for web development including front-end, back-end, and DevOps-related technology. ✨
    <br />
    <br />
    ✨ 我叫黄永谦, 我毕业于RMIT(皇家墨尔本理工大学)信息技术系, 现在在广州作为Ruby开发工程师工作。
    我对前端, 后端开发以及运维相关技术充满兴趣。 ✨
  </div>
</div>
<div class="home-title">
  关于
</div>
<p class="home-article">
  🥳 🥳 This is my personal website, which will log my journey and my experiences.
</p>

<style>
.heart {
  -webkit-animation: breathing 1s ease-out infinite normal;
  animation: breathing 1s ease-out infinite normal;
}

@-webkit-keyframes breathing {
  0% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }

  25% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }

  60% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }

  100% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }
}

@keyframes breathing {
  0% {
    -webkit-transform: scale(0.9);
    -ms-transform: scale(0.9);
    transform: scale(0.9);
  }

  25% {
    -webkit-transform: scale(1);
    -ms-transform: scale(1);
    transform: scale(1);
  }

  60% {
    -webkit-transform: scale(0.9);
    -ms-transform: scale(0.9);
    transform: scale(0.9);
  }

  100% {
    -webkit-transform: scale(0.9);
    -ms-transform: scale(0.9);
    transform: scale(0.9);
  }
}
</style>

app/views/layouts/_categories.html.erb
<div class="flex flex-col cate-card px-4 py-6 max-w-sm rounded-lg shadow-md">
  <ul class="">
    <% categories.each do |category| %>
      <li class="mt-2">
        <%= link_to "- #{category.name}", "articles?category_id=#{category.id}", class: 'text-gray-700 font-bold mx-1 hover:text-gray-600 hover:underline' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<nav class="nav-bg px-6 py-4">
  <div class="flex flex-col container mx-auto md:flex-row md:items-center space-x-4">
      <div class="flex justify-between items-center md:mr-2">
          <div>
              <a class="text-xl font-bold md:text-2xl" href="/">Serendipity</span></a>
          </div>
          <div>
              <button type="button" id="expend" class="block text-gray-800 hover:text-gray-600 focus:text-gray-600 focus:outline-none md:hidden">
                  <svg class="h-6 w-6 fill-current" viewBox="0 0 24 24">
                      <path d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/>
                  </svg>
              </button>
          </div>
      </div>
      <div class="flex flex-col md:flex-row md:mx-4 transition hidden md:block" id="menu">
          <a class="my-1 text-gray-800 hover:text-blue-500 md:mx-4 md:my-0" href="/"><%= t('home') %></a>
          <a class="my-1 text-gray-800 hover:text-blue-500 md:mx-4 md:my-0" href="/articles"><%= t('articles') %></a>
          <% if verified? %>
            <%= link_to 'New category', new_category_path, class: 'my-1 text-gray-800 hover:text-red-500 md:mx-4 md:my-0' %>
            <%= link_to 'New Article', new_article_path, class: 'my-1 text-gray-800 hover:text-red-500 md:mx-4 md:my-0' %>
          <% end %>
      </div>
  </div>
</nav>

<script>
var isOpen = false;

document.getElementById('expend').addEventListener('click', function() {
    isOpen = !isOpen;

    if (isOpen) {
        document.getElementById('menu').classList.remove('hidden');
    } else {
        document.getElementById('menu').classList.add('hidden');
    }
})

</script>

<style>
#menu {
    transition:visibility 0.3s linear,opacity 0.3s linear;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('u_story') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "github-dark.min" %>
    <%= javascript_include_tag "highlight.min" %>
    <%= javascript_include_tag "farbic.min" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="font-roboto">
    <% flash.each do |color, msg| %>
      <div class="text-<%= color %>-700 bg-<%= color %>-100 text-sm flex p-3 lg" role="alert">
        <%= msg %>
      </div>
    <% end %>
    <div>
      <%= render 'layouts/nav' %>
      <main class="px-6 py-8">
        <div class="flex justify-between container mx-auto mt-2" style="margin-top: 6rem;">
          <div class="w-full lg:w-8/12">
            <%= yield %>
          </div>
          <div class="-mx-8 w-4/12 hidden lg:block">
            <div class="mt-10 px-8">
              <h1 class="mb-4 text-xl font-bold text-gray-700"><%= t('categories') %></h1>
                <%= render 'layouts/categories' %>
            </div>
          </div>
        </div>
      </main>
    </div>
    <script>
      hljs.highlightAll();
    </script>
  </body>
</html>

app/views/letter/index.html.erb
<%= javascript_include_tag "farbic.min" %>
<div class="body" id="body">
  <div class="container">  
  <div class="valentines">
    <div class="envelope"></div>
    <div class="front"></div>
    <div class="card">
    <div class="text">Inventation</br>🦁 & 🌸</br>You And Me</div>
    <div class="heart"></div>
    <div class="hearts">
      <div class="one"></div>
      <div class="two"></div>
      <div class="three"></div>
      <div class="four"></div>
      <div class="five"></div>
    </div>
  </div>
  </div>
  <div class="shadow"></div>
  </div>
</div>
<div id="newEnvlope">
  <div class="container">  
      <div class="hearts">
      <div class="one"></div>
      <div class="two"></div>
      <div class="three"></div>
      <div class="four"></div>
      <div class="five"></div>
    </div>
  <div class="valentines">
    <div class="envelope-two"></div>
    <div class="front"></div>
  </div>
  <div class="shadow"></div>
  </div>
  <img id="test" />
</div>


<script>
  document.querySelector('.container').addEventListener('mouseover', (e) => {
    document.querySelector('.card').style.top = '-90px';
  });

  document.querySelector('.container').addEventListener('mouseout', (e) => {
    document.querySelector('.card').style.top = '0';
  });

  document.querySelector('.container').addEventListener('click', (e) => {
    document.querySelector('.card').style.top = '-90px';

    setTimeout(() => {
      renderFromRemote("<%= render_letter_letter_index_path %>", ".body", () => {
        document.querySelector('body').style.backgroundColor = '#03071e';

          const canvas = new fabric.Canvas(document.getElementById('sign'));
          canvas.isDrawingMode = true;
          canvas.freeDrawingBrush.width = 5;
          canvas.freeDrawingBrush.color = "white";
          canvas.setWidth(1000);
          canvas.setHeight(300);

          document.querySelector('.message-btn').addEventListener('click', (e) => {
           const base64image = document.getElementById('sign').toDataURL("image/png").replace("image/png", "image/octet-stream");
           fetch('/sign_images', {
             method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest'
              },
              body: JSON.stringify({ sign_image: { src: base64image } })
           }).then((res) => { console.log(res) })

            document.querySelector('#countdown').style.display = 'none';
            document.querySelector('#newEnvlope').style.display = 'block';
            document.querySelector('body').style.backgroundColor = '#fae1dd';
            clearInterval(x);
          })
      });

      // Set the date we're counting down to
      var countDownDate = new Date("May 20, 2022 00:00:00").getTime();

      // Update the count down every 1 second
      var x = setInterval(() => {

        // Get today's date and time
        var now = new Date().getTime();

        // Find the distance between now and the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        document.querySelector('#days').innerHTML = days;
        document.querySelector("#hours").innerHTML = hours;
        document.querySelector("#mins").innerHTML = minutes;
        document.querySelector("#seconds").innerHTML = seconds

        // If the count down is finished, write some text
        if (distance < 0) {
          clearInterval(x);
        }
      }, 1000);

     }, 1000);
      
    function renderFromRemote(url, element, callback) {
      const xhr = new XMLHttpRequest();
      xhr.open("GET", url, true);
      xhr.onreadystatechange = function() {
      if (xhr.readyState === 4) {
          const { response } = xhr;
          document.querySelector(element).innerHTML = response;
          callback()
        }
      }
      xhr.send({});
    }
  })
</script>

<style>
@font-face {
  font-family: 'pinying';
  font-style: normal;
  font-weight: 400;
  src: url(<%= asset_path 'pinying.ttf' %>) format('truetype');
}

#newEnvlope{
  display: none;
  margin-top: 40vh;
}


body {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #fae1dd;
  transition: background-color 1000ms linear;
  font-family: 'pinying';
}

.container {
  position: relative;
}

.valentines {
  position: relative;
  top:50px;
  cursor: pointer;
  animation: up 3s linear infinite;
}

@keyframes up {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-30px);
  }
}


.envelope {
  position: relative;
  width: 300px;
  height:200px;
  background-color: #f08080; 
}

.envelope-two {
  position: relative;
  width: 300px;
  height:200px;
  background-color: #f08080; 
}

.envelope:before {
  background-color: #f08080; 
  content:"";
  position: absolute;
  width: 212px;
  height: 212px;
  transform: rotate(45deg);
  top:-105px;
  left:44px;
  border-radius:30px 0 0 0;
}

.card {
  position: absolute;
  background-color: #eae2b7;
  width: 270px;
  height: 170px;
  top:5px;
  left:15px;
  box-shadow: -5px -5px 100px rgba(0,0,0,0.4); 
  transition: top 0.8s;
  -moz-transition:top 0.8s; /* Firefox 4 */
  -webkit-transition:top 0.8s; /* Safari and Chrome */
  -o-transition:top 0.8s;
}

.card:before {
  content:"";
  position: absolute;
  border:3px solid #003049;
  border-style: dotted;
  width: 240px;
  heighT: 140px;
  left:12px;
  top:12px;
}

.text {
  position: absolute;
  font-family: 'Brush Script MT', cursive;
  font-size: 28px;
  text-align: center;
  line-height:25px;
  top:19px;
  left:85px;
  color: #003049;
}

.heart {
  background-color: #d62828;
  display: inline-block;
  height: 30px;
  margin: 0 10px;
  position: relative;
  top: 110px;
  left:105px;
  transform: rotate(-45deg);
  width: 30px;
}

.heart:before,
.heart:after {
  content: "";
  background-color: #d62828;
  border-radius: 50%;
  height: 30px;
  position: absolute;
  width: 30px;
}

.heart:before {
  top: -15px;
  left: 0;
}

.heart:after {
  left: 15px;
  top: 0;
}

.hearts {
  position: absolute  
}

.one, .two, .three, .four, .five {
  background-color: red;
  display: inline-block;
  height: 10px;
  margin: 0 10px;
  position: relative;
  transform: rotate(-45deg);
  width: 10px;
  top:50px;
}

.one:before,
.one:after, .two:before, .two:after, .three:before, .three:after, .four:before, .four:after, .five:before, .five:after {
  content: "";
  background-color: red;
  border-radius: 50%;
  height: 10px;
  position: absolute;
  width: 10px;
}

.one:before, .two:before, .three:before, .four:before, .five:before {
  top: -5px;
  left: 0;
}

.one:after, .two:after, .three:after, .four:after, .five:after {
  left: 5px;
  top: 0;
}
  
.one {
  left:10px;
  animation: heart 1s ease-out infinite; 
}

.two {
  left:30px;
  animation: heart 2s ease-out infinite; 
}

.three {
  left:50px;
  animation: heart 1.5s ease-out infinite;
}

.four {
  left:70px;
  animation: heart 2.3s ease-out infinite;
}

.five {
  left:90px;
  animation: heart 1.7s ease-out infinite;
}

@keyframes heart {
  0%{
    transform: translateY(0) rotate(-45deg) scale(0.3);
    opacity: 1;
  }
  100%{
    transform: translateY(-150px) rotate(-45deg) scale(1.3);
    opacity: 0.5;
  }
}

.front {
  position: absolute;
  border-right: 180px solid #f4978e;
  border-top: 95px solid transparent;
  border-bottom: 100px solid transparent;
  left:120px;
  top:5px;
  width:0;
  height:0;
  z-index:10;
}

.front:before {
  position: absolute;
  content:"";
  border-left: 300px solid #f8ad9d;
  border-top: 195px solid transparent;
  left:-120px;
  top:-95px;
  width:0;
  height:0;
}

.shadow {
  position: absolute;
  width: 330px;
  height: 25px;
  border-radius:50%;
  background-color: rgba(0,0,0,0.3);
  top:265px;
  left:-15px;
  animation: scale 3s linear infinite;
  z-index:-1;
}

@keyframes scale {
  0%, 100% {
    transform: scaleX(1);
  }
  50% {
    transform: scaleX(0.85);
  }
}
</style>